# Site settings
title: Služby BOZP a PO s.r.o.
name: Jiří Syrový
url: http://bozp-po-syrovy.eu
description: "Zajišťujeme komplexní služby v BOZP a PO, včetně koordinace staveb."
keywords: "bozp, po"
form_key: xpzdjbvy

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jiří Syrový
  location: Služby BOZP a PO s.r.o.

# Postal address (add as many lines as necessary)
address:
  - line: Jiří Syrový
  - line: Prokopa Velikého 718
  - line: Vysoké Mýto
  - line: <a href="mailto:jiri.syrovy@unet.cz" style="color:white;">jiri.syrovy@unet.cz</a>

# Build settings
markdown: kramdown
permalink: pretty
